live_config_reload = true

import = [
    # "~/.config/alacritty/rose-pine.toml",
    # "~/.config/alacritty/gruvbox-material.toml"
    "~/.config/alacritty/catppuccin-mocha.toml",
]
# import = ["~/.config/alacritty/gruvbox-material.toml"]

[env]
TERM = "xterm-256color"

# Font settings
[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# Window settings
[window.padding]
x = 5
y = 5

[window]
decorations = "Buttonless"
opacity = 0.95
option_as_alt = "Both"
