# iterm2
add_newline = true

[character]
# iterm2
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[gcloud]
disabled = true

[aws]
disabled = true

[ruby]
disabled = true

[lua]
disabled = true

[docker_context]
disabled = true
