live_config_reload = true

import = [
    "~/.config/alacritty/rose-pine.toml",
    # "~/.config/alacritty/tokyonight.toml",
    # "~/.config/alacritty/rose-pine-moon.toml",
    # "~/.config/alacritty/gruvbox-material.toml"
    # "~/.config/alacritty/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Beam"

# Font settings
[font]
size = 10.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# Window settings
[window.padding]
x = 5
y = 5

[window]
decorations = "Buttonless"
opacity = 0.97
option_as_alt = "Both"
